plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/aaronsembrano/Desktop/Pool Cleaners/cantara-cleaning"
publishOrigin = "default"
base = "/Users/aaronsembrano/Desktop/Pool Cleaners/cantara-cleaning"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]